[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.kv]
STAGE = "production"
NODE_ENV = "production"
FRONTEND_URL = "https://nuvex-complete-p0k0h7d3a-gustavodev25s-projects.vercel.app"
